### PR TITLE
Setup initialized

### PR DESCRIPTION
**Pull request by jaylenw**
I was able to get the project up and running with these project settings.

@Linux4Hope/spero please open this project and make sure you are able to build and run the project. Once everyone is able to setup the project we will then have @nguym077 merge it in. Once you are able to get up and going, comment that you are all set up.

### CODE REVIEW

**Comment by ghost** [comment]
Got it all up and going :-)

**Review by jaylenw — COMMENTED** [review]
@nguym077 when you ran your build, this file was automatically generated? Now they are two .iml files where there should only be one. I know this is a test commit but now I want to know if the project was setup correctly. This file is called spero.iml and the one i pushed is sperobackend.iml. Wondering why your intellij generated another one?

**Comment by ghost** [comment]
uhh... idk? I just cloned whatever was here and ran it.

**Comment by jaylenw** [comment]
Okay lets see what occurs when the rest of the team clones and build. Let us know if either .iml gets generated or updated.

**Comment by ghost** [comment]
I tried deleting the spero.iml, reimporting the project, and then running it again, and its automatically regenerated.. ?

**Comment by jaylenw** [comment]
My latest changes are pushed. This should allow us to open the project correctly. If you already have this imported, delete it. Clone, then open project, not import. My mistake. @Linux4Hope/spero

**Comment by ghost** [comment]
Okay, I'm finally all set up (again) :-)

**Review by jaylenw — COMMENTED** [review]
@cheriejw did you import project or open project? There shouldn't be an *.xml files modified for this branch.

**Review by ghost — APPROVED** [review]

**Pull request merged**
